apiVersion: v1
kind: Service
metadata:
  name: makeline-service
  namespace: app2
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  selector:
    app: makeline-service
