apiVersion: apps/v1
kind: Deployment
metadata:
  name: tileserver
  namespace: app5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tileserver
  template:
    metadata:
      labels:
        app: tileserver
    spec:
      hostNetwork: true
      containers:
      - name: tileserver
        image: maptiler/tileserver-gl
        ports:
        - containerPort: 8080
